### PR TITLE
task-3

### PR DESCRIPTION
**Pull request by BewitchedBySycorax**

### CODE REVIEW

**Comment by shurygindv** [comment]
@BewitchedBySycorax, hey )) where do you hide the code?

**Comment by BewitchedBySycorax** [comment]
Hey!
I’m currently working on it, can you check it later, please?
It would be great if tomorrow morning, ok?
____________________
Faithfully yours,
Aleksei Voitovskii
+7 (916) 877-99-15

**Comment by shurygindv** [comment]
@BewitchedBySycorax, OK

**Comment by NexGenUA** [comment]
accepted

**Comment by shurygindv** [comment]
@BewitchedBySycorax , how are you?)

**Comment by BewitchedBySycorax** [comment]
Hi!
Mark it as zero) I’m currently doing test task for work
0 points - it’s ok for task 3
____________________
Faithfully yours,
Aleksei Voitovskii
+7 (916) 877-99-15

**Comment by shurygindv** [comment]
@BewitchedBySycorax, ok, if you need a review later (score), you know who can it ))

**Comment by BewitchedBySycorax** [comment]
👌
____________________
Faithfully yours,
Aleksei Voitovskii
+7 (916) 877-99-15

**Pull request merged**
